[dependencies]
"shira/php" = "8.5.10"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "shira/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-d", "display_errors=Off", "-d", "expose_php=Off", "-t", "/app/public", "-S", "0.0.0.0:8080"]